# Generated by Django 5.2.11 on 2026-03-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_game_platform_game_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='cover_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='GameEntry',
        ),
    ]
